import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  main: {
    width: "80%",
    margin: "30px auto",
    "@media screen and (max-width: 1268px)": {
      width: "90%",
    },
    "& nav": {
      display: "flex",
      justifyContent: "space-between",
      "& h1": {
        fontSize: "24px",
        fontWeight: 400,
        fontFamily: "Rubik",
      },
      "& .icons": {
        width: "80px",
        display: "flex",
        justifyContent: "space-between",
      },
    },
    "& span": {
      display: "block",
      width: "100%",
      marginTop: "27px",
      margin: "auto",
      height: "1px",
      background: "#F4F6FC",
    },
    "& section": {
      display: "flex",
      "& span": {
        display: "block",
        width: "2px",
        height: "100vh",
        margin: "0px 10px",
        backgroundColor: "#F4F6FC",
      },
      "& nav": {
        width: "60%",
        display: "flex",
        justifyContent: "flex-start",
        flexDirection: "column",
        marginTop: "27px",
        "& .title": {
          textAlign: "start",
          fontSize: "20px",
        },
        "& .projects": {
          display: "flex",
          justifyContent: "space-evenly",
          flexWrap: "wrap",
          "& .project": {
            width: "114px",
            height: "155px",
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-evenly",
            marginTop: "24px",
            alignItems: "center",
            borderRadius: "8px",
            "&:hover": {
              backgroundColor: "#E8F0FE",
              cursor: "pointer",
            },
            "& .rec": {
              width: "80px",
              height: "80px",
              display: "flex",
              justifyContent: "space-around",
              borderRadius: "12px",
              textAlign: "center",
              alignItems: "center",
              alignContent: "center",
              fontSize: "26px",
              fontWeight: 500,
              fontFamily: "Rubik",
              marginBottom: "24px",
              color: "#FFFFFF",
            },
            "& .pro-title": {
              color: "#838895",
              fontSize: "16px",
              fontWeight: 400,
              fontFamily: "Rubik",
              height: "30px",
            },
          },
        },
        "& .rec": {
          background: "#E8F0FE",
          borderRadius: "8px",
          width: "100%",
          height: "170px",
          display: "flex",
          justifyContent: "flex-start",
          alignItems: "end",
          marginBottom: "40px",
          "& section": {
            width: "60%",
            height: "100%",
            display: "flex",
            flexDirection: "column",
            justifyContent: "flex-start",
            alignContent: "start",
            "& .title": {
              fontSize: "24px",
              fontWeight: 400,
              fontFamily: "Rubik",
              color: "#31394E",
              textAlign: "left",
              marginTop: "25px",
              marginLeft: "25px",
              marginBottom: "15px",
            },
            "& .sub": {
              fontSize: "14px",
              marginLeft: "25px",
              fontWeight: 400,
              fontFamily: "Rubik",
              color: "#31394E",
              textAlign: "left",
              "& strong": {
                fontSize: "14px",
                fontWeight: 600,
                fontFamily: "Rubik",
                color: "#31394E",
              },
            },
          },
          "& img": {
            width: "220px",
            height: "190px",
            zIndex: "1",
          },
        },
      },
      "& .tasks": {
        width: "40%",
        display: "flex",
        flexDirection: "column",
        "& nav": {
          width: "100%",
          height: "70px",
          margin: "0px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
          flexDirection: "row",
          "& .title": {
            fontSize: "26px",
            fontWeight: 600,
            fontFamily: "Rubik",
            color: "#4C84FF",
          },
          "& h5": {
            fontSize: "12px",
            fontWeight: 400,
            display: "flex",
            alignItems: "center",
            alignContent: "center",
            fontFamily: "Rubik",
            color: "#838895",
            "&:hover": {
              cursor: "pointer",
            },
          },
        },
        "& .list": {
          "& span": {
            width: "100%",
            height: "2px",
            color: "background: rgb(244, 246, 252)",
            marginTop: "5px",
            marginBottom: "5px"
          },
          "& .card": {
            width: "95%",
            margin: "auto",
            display: "flex",
            justifyContent: "flex-start",
            "& .prio": {
              width: "10%",
              display: "flex",
              alignItems: "center",
            },
            "& .type": {
              width: "10%",
              display: "flex",
              alignItems: "center",
            },
            "& .code": {
              width: "20%",
              display: "flex",
              alignItems: "center",
              "& h1": {
                fontSize: "14px",
                fontWeight: 600,
                fontFamily: "Rubik",
              },
            },
            "& .title": {
              width: "40%",
              display: "flex",
              alignItems: "center",
              "& h2": {
                fontSize: "14px",
                height: "18px",
                textAlign: "left",
                fontWeight: 400,
                fontFamily: "Rubik",
                overflow: "hidden",
                textOverflow: "ellipsis",
              },
            },
            "& .other": {
              width: "70px",
              height: "18px",
              borderRadius: "6px",
              display: "flex",
              justifyContent: "center",
              textAlign: "center",
              alignItems: "center",
              "& h5": {
                fontSize: "12px",
                fontWeight: 400,
                fontFamily: "Rubik",
                color: "#ffffff",
               
              },
            },
          },
        },
        "& .head": {
          width: "110px",
          height: "90px",
          alignItems: "center",
          alignContent: "center",
          display: "flex",
          justifyContent: "space-between",
          "& h3": {
            fontSize: "20px",
            fontWeight: 400,
            fontFamily: "Rubik",
            color: "#31394E",
          },
          "& div": {
            width: "30px",
            height: "15px",
            borderRadius: "8px",
            backgroundColor: "rgb(0, 121, 255, 0.36)",
            color: "rgb(0, 121, 255)",
            "& h1": {
              fontSize: "12px",
              fontWeight: 400,
              fontFamily: "Rubik",
            },
          },
        },
      },
    },
  },
});
export default useStyles;
