import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  main: {
    width: "80%",
    margin: "30px auto",
    "@media screen and (max-width: 1268px)": {
      width: "90%",
    },
    "& nav": {
      display: "flex",
      justifyContent: "space-between",
      "& section": {
        display: "flex",
        justifyContent: "space-between",
        width: "160px",
        "& h1": {
          color: "#31394E",
          fontSize: "24px",
          fontWeight: 400,
          fontFamily: "Rubik",
        },
      },
      "& .icons": {
        width: "55%",
        display: "flex",
        justifyContent: "space-between",
        "& .iter": {
          width: "250px",
          height: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borderRadius: "4px",
          backgroundColor: "#E8F0FE",
          "& h2": {
            fontSize: "14px",
            fontWeight: 400,
            fontFamily: "Rubik",
            color: "#4C84FF",
          },
        },
        "& button": {
          width: "130px",
          height: "32px",
          border: "none",
          borderRadius: "6px",
          backgroundColor: "#29C293",
          display: "flex",
          justifyContent: "space-evenly",
          alignItems: "center",
          cursor: "pointer",
          "& h3": {
            color: "#FFFFFF",
            fontSize: "14px",
            fontWeight: 600,
            fontFamily: "Rubik",
          },
        },
      },
    },
    "& span": {
      display: "block",
      width: "100%",
      marginTop: "5px",
      margin: "auto",
      height: "2px",
      background: "#F4F6FC",
    },
    "& .search": {
      marginTop: "12px",
      width: "100%",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      "& .left": {
        width: "30%",
        display: "flex",
        alignItems: "center",
        "& .icon": {
          color: " rgba(49, 57, 78, 0.4)",
        },
      },
      "& .right": {
        width: "30%",
        display: "flex",
        justifyContent: "space-evenly",
        alignItems: "center",
        "& button": {
          border: "2px solid rgb(76, 132,255)",
          color: "rgb(76, 132,255)",
          height: "32px",
          width: "129px",
          background: "#ffffff",
          borderRadius: "6px",
          fontSize: "14px",
          cursor: "pointer",
          fontWeight: 600,
          fontFamily: "Rubik",
        },
        "& .link": {
          fontSize: "14px",
          fontWeight: 600,
          fontFamily: "Rubik",
          color: "#ADB0B8",
          textDecoration: "none",
        },
      },
    },
    "& .core": {
      "& .line": {
        display: "flex",
        justifyContent: "flex-start",
        alignContent: "start",
        margin: "35px auto",
        "& .it": {
          fontSize: "14px",
          fontWeight: 600,
          fontFamily: "Rubik",
          color: "rgba(49, 57, 78, 0.5)",
          textAlign: "center",
          width: "10%",
        },
        "& .name": {
          width: "50%",
          textAlign: "left",
        },
      },
      "& ._line": {
        display: "flex",
        justifyContent: "flex-start",
        alignContent: "start",
        margin: "15px auto",
        "& ._it": {
          textAlign: "center",
          width: "10%",
          display: "flex",
          justifyContent: "center",
        },
        "& ._name": {
          display: "flex",
          textAlign: "left",
          alignItems: "center",
          justifyContent: "flex-start",
          width: "50%",
          fontSize: "14px",
          fontWeight: 400,
          fontFamily: "Rubik",
          color: "#31394E",
        },
        "& ._prio": {
          "& .cont": {
            height: "32px",
            width: "80px",
            display: "flex",
            justifyContent: "center",
            textAlign: "center",
            alignItems: "center",
            borderRadius: "6px",
            color: "#FFFFFF",
            fontSize: "12px",
            fontWeight: 400,
            fontFamily: "Rubik",
          },
        },
        "& ._status": {
          "& .cont": {
            height: "32px",
            width: "80px",
            display: "flex",
            justifyContent: "center",
            textAlign: "center",
            alignItems: "center",
            borderRadius: "6px",
            color: "#FFFFFF",
            fontSize: "12px",
            fontWeight: 400,
            fontFamily: "Rubik",
            background: "#D6D7DC",
          },
        },
        "& ._date": {
          color: "rgba(49, 57, 78, 0.5)",
          fontSize: "12px",
          fontWeight: 400,
          fontFamily: "Rubik",
          display: "flex",
          justifyContent: "center",
          textAlign: "center",
          alignItems: "center",
        },
        "& ._check": {
          color: "rgba(49, 57, 78, 0.5)",
          fontSize: "12px",
          fontWeight: 400,
          fontFamily: "Rubik",
          display: "flex",
          justifyContent: "center",
          textAlign: "center",
          alignItems: "center",
        },
        "& ._assi": {
          "& .cont": {
            display: "flex",
            justifyContent: "flex-end",
            "& .img1": {
              position: "relative",
              left: "12px",
            },
            "& .img2": {
              position: "relative",
              right: "12px",
            },
          },
        },
      },
    },
  },
});
export default useStyles;
