import { createUseStyles } from "react-jss";

const useStyles = createUseStyles({
  second: {
    width: "500px",
    position: "absolute",
    overflowY: "scroll",
    right: "0px",
    top: "0px",
    background: "#ffffff",
    border: "2px solid #E8F0FE",
    height: "100%",
    zIndex: 8,
    transition:" 0.4s all ease",
    "&:focus": {
      border: "2px solid #E8F0FE",
    },

    "&::-webkit-scrollbar": {
      width: "5px",
    },

    "::-webkit-scrollbar-track": {
      background: "#fff",
    },

    "::-webkit-scrollbar-thumb": {
      background: "#c2c2c2",
      borderRadius: "10px",
    },

    "&::-webkit-scrollbar-thumb:hover": {
      background: "#919090",
    },
    "& nav": {
      height: "50px",
      borderBottom: "2px solid #E8F0FE",
      display: "flex",
      justifyContent: "flex-end",
      alignItems: "center",
      "& img": {
        margin: "auto 12px",
        cursor: "pointer"
      },
    },
    "& .core": {
      "& h1": {
        fontWeight: 600,
        fontSize: "24px",
        fontFamily: "Rubik",
        margin: "24px",
        textAlign: "left",
        color: "rgb(21, 27, 38)",
      },
      "& h5": {
        fontWeight: 400,
        fontSize: "12px",
        marginLeft: "32px",
        fontFamily: "Rubik",
        textAlign: "left",
        color: " #ADB0B8",
      },
      "& p": {
        width: "390px",
        color: "rgba(21, 27, 38, 0.5)",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "left",
        marginLeft: "32px",
        fontFamily: "Rubik",
        marginTop: "14px",
      },
      "& h6": {
        color: "#ADB0B8",
        fontWeight: 400,
        fontSize: "12px",
        textAlign: "left",
        marginLeft: "24px",
        fontFamily: "Rubik",
        marginTop: "24px",
      },
      "& .prio": {
        width: "120px",
        alignItems: "center",
        display: "flex",
        justifyContent: "space-evenly",
        marginLeft: "32px",
        marginTop: "14px",
        "& h3": {
          color: "#31394E",
          fontWeight: 400,
          fontSize: "14px",
          fontFamily: "Rubik",
        },
        "& img": {},
      },
      "& .date": {
        color: "#31394E",
        fontWeight: 400,
        fontSize: "14px",
        fontFamily: "Rubik",
        textAlign: "left",
        margin: "14px 0px 30px 32px",
      },
      "& .title": {
        width: "90%",
        margin: "33px 0px 0px 33px",
        display: "flex",
        justifyContent: "space-between",
        "& h1": {
          color: "#4C84FF",
          fontWeight: 600,
          margin: "0px",
          fontSize: "12px",
          fontFamily: "Rubik",
        },
      },
      "& .assi": {
        margin: "14px 32px",
        display: "flex",
        "& .rec": {
          background: "rgba(0, 121, 255, 0.2963)",
          borderRadius: "7.5px",
          marginRight: "8px",
          width: "160px",
          height: "36px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-evenly",
          cursor: "pointer",
          "& h3": {
            color: "#0079FF",
            fontWeight: 400,
            fontSize: "12.5px",
            fontFamily: "Rubik",
          },
        },
      },
      "& .rec": {
        width: "100%",
        height: "50px",
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        "&:hover": {
          background: "#E8F0FE",
          cursor: "pointer"
        },
        "& div": {
          display: "flex",
          alignItems: "center",
          width: "20%",
          justifyContent: "space-evenly",
        },
        "& h1": {
          color: "#000000",
          fontSize: "14px",
          fontWeight: 400,
          fontFamily: "Rubik",
        },
      },
    },
  },
  main: {
    width: "80%",
    margin: "30px auto",
    "@media screen and (max-width: 1268px)": {
      width: "90%",
    },
    "& nav": {
      display: "flex",
      justifyContent: "space-between",
      "& section": {
        display: "flex",
        justifyContent: "space-between",
        width: "160px",
        "& h1": {
          color: "#31394E",
          fontSize: "24px",
          fontWeight: 400,
          fontFamily: "Rubik",
        },
      },
      "& .icons": {
        width: "55%",
        display: "flex",
        justifyContent: "space-between",
        "& .iter": {
          width: "250px",
          height: "32px",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          borderRadius: "4px",
          backgroundColor: "#E8F0FE",
          "& h2": {
            fontSize: "14px",
            fontWeight: 400,
            fontFamily: "Rubik",
            color: "#4C84FF",
          },
        },
        "& button": {
          width: "130px",
          height: "32px",
          border: "none",
          borderRadius: "6px",
          backgroundColor: "#29C293",
          display: "flex",
          justifyContent: "space-evenly",
          alignItems: "center",
          cursor: "pointer",
          "& h3": {
            color: "#FFFFFF",
            fontSize: "14px",
            fontWeight: 600,
            fontFamily: "Rubik",
          },
        },
      },
    },
    "& span": {
      display: "block",
      width: "100%",
      marginTop: "5px",
      margin: "auto",
      height: "2px",
      background: "#F4F6FC",
    },
    "& .search": {
      marginTop: "12px",
      width: "100%",
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
      "& .left": {
        width: "30%",
        display: "flex",
        alignItems: "center",
        "& .icon": {
          color: " rgba(49, 57, 78, 0.4)",
        },
      },
      "& .right": {
        width: "30%",
        display: "flex",
        justifyContent: "space-evenly",
        alignItems: "center",
        "& button": {
          border: "2px solid rgb(76, 132,255)",
          color: "rgb(76, 132,255)",
          height: "32px",
          width: "129px",
          background: "#ffffff",
          borderRadius: "6px",
          fontSize: "14px",
          cursor: "pointer",
          fontWeight: 600,
          fontFamily: "Rubik",
        },
        "& .link": {
          fontSize: "14px",
          fontWeight: 600,
          fontFamily: "Rubik",
          color: "#ADB0B8",
          textDecoration: "none",
        },
      },
    },
    "& .core": {
      "& .line": {
        display: "flex",
        justifyContent: "flex-start",
        alignContent: "start",
        margin: "35px auto",
        "& .it": {
          fontSize: "14px",
          fontWeight: 600,
          fontFamily: "Rubik",
          color: "rgba(49, 57, 78, 0.5)",
          textAlign: "center",
          width: "10%",
        },
        "& .name": {
          width: "50%",
          textAlign: "left",
        },
      },
      "& ._line": {
        display: "flex",
        justifyContent: "flex-start",
        alignContent: "start",
        margin: "15px auto",
        "& ._it": {
          textAlign: "center",
          width: "10%",
          display: "flex",
          justifyContent: "center",
        },
        "& ._name": {
          display: "flex",
          textAlign: "left",
          alignItems: "center",
          justifyContent: "flex-start",
          width: "50%",
          fontSize: "14px",
          fontWeight: 400,
          fontFamily: "Rubik",
          color: "#31394E",
        },
        "& ._prio": {
          "& .cont": {
            height: "32px",
            width: "80px",
            display: "flex",
            justifyContent: "center",
            textAlign: "center",
            alignItems: "center",
            borderRadius: "6px",
            color: "#FFFFFF",
            fontSize: "12px",
            fontWeight: 400,
            fontFamily: "Rubik",
          },
        },
        "& ._status": {
          "& .cont": {
            height: "32px",
            width: "80px",
            display: "flex",
            justifyContent: "center",
            textAlign: "center",
            alignItems: "center",
            borderRadius: "6px",
            color: "#FFFFFF",
            fontSize: "12px",
            fontWeight: 400,
            fontFamily: "Rubik",
            background: "#D6D7DC",
          },
        },
        "& ._date": {
          color: "rgba(49, 57, 78, 0.5)",
          fontSize: "12px",
          fontWeight: 400,
          fontFamily: "Rubik",
          display: "flex",
          justifyContent: "center",
          textAlign: "center",
          alignItems: "center",
        },
        "& ._check": {
          color: "rgba(49, 57, 78, 0.5)",
          fontSize: "12px",
          fontWeight: 400,
          fontFamily: "Rubik",
          display: "flex",
          justifyContent: "center",
          textAlign: "center",
          alignItems: "center",
        },
        "& ._assi": {
          "& .cont": {
            display: "flex",
            justifyContent: "flex-end",
            "& .img1": {
              position: "relative",
              left: "8px",
            },
            "& .img2": {
              position: "relative",
              right: "8px",
            },
          },
        },
      },
    },
  },
});
export default useStyles;
